---
kind: Service
apiVersion: v1
metadata:
  name: nemotron-rerank-1b
  labels:
    app: nemotron-rerank-1b
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: nemotron-rerank-1b
