{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kong-gateway.fullname" . }}-route
  labels:
    {{- include "kong-gateway.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "kong-gateway.fullname" . }}
    weight: 100
  port:
    targetPort: proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}