apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-gateway.fullname" . }}
  labels:
    {{- include "kong-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.proxy.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: {{ .Values.service.ports.proxy-tls.port }}
      targetPort: proxy-tls
      protocol: TCP
      name: proxy-tls
    - port: {{ .Values.service.ports.admin.port }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ .Values.service.ports.admin-tls.port }}
      targetPort: admin-tls
      protocol: TCP
      name: admin-tls
    - port: {{ .Values.service.ports.status.port }}
      targetPort: status
      protocol: TCP
      name: status
  selector:
    {{- include "kong-gateway.selectorLabels" . | nindent 4 }}