{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kong-gateway.fullname" . }}
  labels:
    {{- include "kong-gateway.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "kong-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.ports.status.name }}
      interval: 30s
      path: /metrics
{{- end }}