# Control Plane values for Kong Hybrid Mode
# Based on: https://github.com/Kong/charts/blob/main/charts/kong/README.md#hybrid-mode

deployment:
  kong:
    enabled: true
  revisionHistoryLimit: 10
  serviceAccount:
    create: true
    automountServiceAccountToken: false
  daemonset: false
  hostNetwork: false
  hostname: "cp"
  prefixDir:
    sizeLimit: 256Mi
  tmpDir:
    sizeLimit: 1Gi

env:
  role: control_plane
  database: "postgres"
  router_flavor: "traditional"
  nginx_worker_processes: "2"
  proxy_access_log: /dev/stdout
  admin_access_log: /dev/stdout
  proxy_error_log: /dev/stderr
  admin_error_log: /dev/stderr
  prefix: /kong_prefix/
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

envFrom: []

# extraLabels:
#   app.kubernetes.io/component: ai-gateway-cp

image:
  repository: kong
  tag: "3.9"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "kong-cp"

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
    parameters: []
  tls:
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters:
    - http2
    client:
      caBundle: ""
      secretName: ""
  ingress:
    enabled: false

status:
  enabled: true
  http:
    enabled: true
    containerPort: 8100
    parameters: []
  tls:
    enabled: false
    containerPort: 8543
    parameters: []

cluster:
  enabled: true
  type: ClusterIP
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005
    parameters: []
  ingress:
    enabled: false

proxy:
  enabled: false
  type: ClusterIP
  nameOverride: ""
  annotations: {}
  labels:
    enable-metrics: "true"
  http:
    enabled: false
    servicePort: 80
    containerPort: 8000
    parameters: []
  tls:
    enabled: false
    servicePort: 443
    containerPort: 8443
    parameters:
    - http2
    appProtocol: ""
  stream: []
  ingress:
    enabled: false

udpProxy:
  enabled: false
  type: LoadBalancer
  stream: []

plugins: {}

secretVolumes:
- kong-cluster-cert

migrations:
  preUpgrade: false
  postUpgrade: false

dblessConfig:
  configMap: ""
  secret: ""
  config: |

ingressController:
  enabled: false
  gatewayDiscovery:
    enabled: false
    generateAdminApiService: false
    adminApiService:
      namespace: ""
      name: ""

postgresql:
  enabled: false

certificates:
  enabled: false
  issuer: ""
  clusterIssuer: ""
  proxy:
    enabled: true
    issuer: ""
    clusterIssuer: ""
    commonName: "app.example"
    dnsNames: []
  admin:
    enabled: true
    issuer: ""
    clusterIssuer: ""
    commonName: "kong.example"
    dnsNames: []

waitImage:
  enabled: false
  pullPolicy: IfNotPresent

updateStrategy: {}

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"

initContainerResources: {}

readinessProbe:
  httpGet:
    path: "/status/ready"
    port: status
    scheme: HTTP
  initialDelaySeconds: 5
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: "/status"
    port: status
    scheme: HTTP
  initialDelaySeconds: 5
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

lifecycle:
  preStop:
    exec:
      command:
        - kong
        - quit
        - '--wait=15'

terminationGracePeriodSeconds: 30

tolerations: []

nodeSelector: {}

podAnnotations: {}

# podLabels:
#   app.kubernetes.io/component: ai-gateway-cp

replicaCount: 1

deploymentAnnotations: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  annotations: {}
  behavior: {}
  targetCPUUtilizationPercentage: ""
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

podDisruptionBudget:
  enabled: false
  unhealthyPodEvictionPolicy: IfHealthyBudget

priorityClassName: ""

securityContext:
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: false

serviceMonitor:
  enabled: true
  trustCRDsExist: false
  # labels:
    # app.kubernetes.io/component: ai-gateway-cp

enterprise:
  enabled: false

extraConfigMaps: []
extraSecrets: []
extraObjects: []
